### PR TITLE
Chore: Populate sample recipes

### PR DESCRIPTION
**Pull request by blaketingyu**
Chore: Populate sample recipes

### CODE REVIEW

**Review by yusufaine — APPROVED** [review]
LGTM! Just curious about why you chose to separate the RecipeList out of SampleDataUtil

**Comment by blaketingyu** [comment]
> LGTM! Just curious about why you chose to separate the RecipeList out of SampleDataUtil

Hello. I wanted to have a specific class just to populate the recipes. `SampleDataUtil` had other methods to get ingredients and stuff.

**Review by Oddcorner — APPROVED** [review]
LGTM! 👍

**Review by aidanaden — APPROVED** [review]
LGTM! 1 step closer to finishing this 👅

**Pull request merged**
